### ISSUE TITLE
Category description doesn't display

### ISSUE THREAD

**Issue by brilliantweb** [JoomGallery/BootOne#11]
I am using Boot3.
The category title and description do not show

If I leave all other settings unchanged on the menu item, and just revert back to the default layout, then the title and descriptions appear.

**Comment by Chraneco** [comment]
In which view is it not displayed? Could you please post a screenshot?

**Comment by brilliantweb** [comment]
Category and Sub-category views.
If I change the menu item type back to the default JoomGallery category layout, then the title and description show.  So, JoomGallery is configured correctly, but the bootone template is not.

See http://www.new.sarahrichards.co.za/index.php?option=com_joomgallery&view=category&layout=bootone&catid=2

Regards
Brendon

**Comment by Chraneco** [comment]
You are using a template override or a modified version for the default layout which makes the category description appear there.
By default, the category description is not displayed in the category view if only sub-categories are present.

BootThree behaves in the same way, so the category description is not displayed there either (but this might change before we release a stable version of the layout).

For now you will have to create a template override for BootThree as well.

**Comment by brilliantweb** [comment]
Completely forgot about that override.
I applied the override to bootone.php and everything is how I want it.

The override instructions are here: http://www.forum.en.joomgallery.net/index.php?topic=7024.msg21823#msg21823

Thanks
