### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Erftralle** [JoomGallery/BootOne#2]
First of all, thank you very much for providing BootOne.

Just wanted to start to play around with it as I got the following error message during install:

> Warning
> JInstaller: :Install: File does not exist ..\BootOne-master\components\com_joomgallery\views\upload\tmpl\bootone_ajax.php

**Comment by Chraneco** [comment]
Sorry, some files are only in the BootThree branch. The latest release (Alpha 3) should fix this.

**Comment by Erftralle** [comment]
Thanks, the latest release does fix it.
