### ISSUE TITLE
BootOne does not show up

### ISSUE THREAD

**Issue by Erftralle** [JoomGallery/BootOne#3]
Although I've created a menu item `JoomGallery » Gallery View: Bootstrapped` and set `Alternative Layout` to `bootone` the BootOne layout does not show. The default template is still used.

Joomla! 3.4.1
JoomGallery 3.2.1

**Comment by Chraneco** [comment]
Maybe something went wrong during the installation. Does the file
`components/com_joomgallery/views/gallery/tmpl/bootone.php`
exist?

When SEF is disabled, does the parameter `layout=bootone` appear in the URL of the menu item?

**Comment by Erftralle** [comment]
The `layout=bootone` appears in the URL and the file `components/com_joomgallery/views/gallery/tmpl/bootone.php` is present too.

I found out, that the problem was caused by the use of symbolic links. I forked `BootOne` and cloned it to my desktop to a directory outside of my web folder. Than I created symbolic links of all files and directories `BootOne` needs to the clone directory. I proceed always that way, also for other clones (e.g. JoomGallery) and I never detected any problem, until today. This way, you can have different components, modules and plugins in a single Joomla! installation. For me, it does make things easier.

The linked files were not detected by Joomla! because some lines in JPath::find()

```
            /*
             * The substr() check added to make sure that the realpath()
             * results in a directory registered so that
             * non-registered directories are not accessible via directory
             * traversal attempts.
             */
            if (file_exists($fullname) && substr($fullname, 0, strlen($path)) == $path)
            {
                return $fullname;
            }
```

do prevent that. For me, this is a bug or at least not the job of Joomla!. What do you think?

I have to apologize, it has been not a problem of this package!

May I ask a question? How do you proceed when cloning a project to make it as easy as possible.

**Comment by Chraneco** [comment]
Interesting way to do that, I always just have several `.git` directories in the root of Joomla. For example,
`joomgallery.git`
`bootone.git`

If I want to commit or push/pull from/to a specific repository I need to rename the respective directory first:
`mv bootone.git .git`

This of course still has the disadvantage that there will always be a lot of untracked files because they belong to other repositories. I have to make sure that I don't accidentally include them while executing a `git add`.

Your approach probably doesn't have this issue. Does it not find the bootone files because the `realpath()` differs from the location where it should be?
It would be worth mentioning this problem at the Joomla issue tracker but it will probably be hard to convince them that this is important enough.

**Comment by Erftralle** [comment]
Thanks for explaining your method of cloning.
Seems to be a risky one, and what about the files in the root directory with the same name (README.MD, .gitignore, LICENSE)?

> Does it not find the bootone files because the realpath() differs from the location where it should be?

Yes, that's right. realpath() returns the path of the link's source.

> It would be worth mentioning this problem at the Joomla issue tracker but it will probably be hard to convince them that this is important enough.

Yes, most probably. I'll think about it.

For the moment I switched over to hard links, which seem to work fine.

**Comment by Chraneco** [comment]
> Seems to be a risky one, and what about the files in the root directory with the same name (README.MD, .gitignore, LICENSE)?

Yeah, I have to make sure that I don't `git add` them, either. If I need one of these files in its correct state of the respective "active" respository it's enough to do a checkout on it:
`git checkout .gitignore`

I guess I have to try this soft/hard links thing, too.

**Comment by Erftralle** [comment]
> For the moment I switched over to hard links, which seem to work fine.

I have to revert my statement. Hard links do not work propper with git and/or Eclipse. When switching between different branches somehow the hard link break. I dont know why.

I opened a Joomla! issue https://github.com/joomla/joomla-cms/issues/7216.
For the moment I will switch back to symbolic links and hack the Joomla! core.

**Comment by Chraneco** [comment]
Not sure whether the answers over there were satisfying, but I guess we can close this issue for now?

**Comment by Erftralle** [comment]
Closing issue.
