### ISSUE TITLE
Description Display - Classes, layout

### ISSUE THREAD

**Issue by GJSchaller** [JoomGallery/BootOne#8]
Example Page: http://template.knightrealms.com/community/gallery/awards/awards-for-march-2015.html

The word "Description:" appears above each description, and cannot be styled separately from the rest of the text (i.e. - hidden, sized, etc. differently from the description itself).

Would it be possible to add a class to this, or make an option to hide it?

**Comment by Chraneco** [comment]
You can use the language override manager of Joomla! for this. Simply putting an empty string for that language constant will remove the word, but you could also place additional HTML there in order to add a CSS class for it.
